### ISSUE TITLE
Download labeled data after using Range slider plot

### ISSUE THREAD

**Issue by raul-rufato** [debiai/debiai#140]
I am not being able to dowload the labeled data after using the Range slider plot on a 1D time series. Is it possible to dowload the data positions in which I applied the range slider selection?

Thank you

**Comment by Tomansion** [comment]
Hello @raul-rufato, thank you for submitting this issue.

If I understand correctly, you have made a selection using the range-slider plot and want to download the selected data and/or the data positions of the selection.

## At the moment

The best way to download the selected data is to create a selection, you will then be able to download it. Depending on the way you have uploaded the data:

- With the Python module: 
```python
...
my_selection = my_project.get_selection("range_slider_selection")
data_df = my_selection.get_tf_dataset()
data_id_list = data_df["my_id_column"]
```

- With the Web data-providers:
You can complete the `POST debiai/projects/{projectId}/selections` route and save the id list in a file for example.

## If you just want to save the range

You can open the  `Export ->` menu on the widget and copy the range in a JSON format :
![image](https://github.com/debiai/debiai/assets/59999324/968804f3-ed2f-492c-b837-71a30811b454)
![image](https://github.com/debiai/debiai/assets/59999324/ed4eaef2-bf06-419d-9a60-cb83294902ae)

You can also create an export method to link the selection with another application. ([More info]( https://debiai.irt-systemx.fr/dashboard/dataExport/#setting-up-export-methods))

## Export CSV

Tell me if a way to download, from the analysis dashboard, the selected data as a CSV file would be best. This feature is planned in our backlog (#88).

If any of this work for you, don't mind suggesting a precise way on how we can improve this. 
Thank you again!

**Comment by Tomansion** [comment]
Hello @raul-rufato, can I have an update on your progress on this issue? Do you still need help?

**Comment by raul-rufato** [comment]
Hello,

I did it by just coping the .json file.
Thank you, it worked!

Regards,

Raul

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Tomansion** [comment]
Great to hear that! 
Please feel free to ask for more assistance whenever you need it.
