### ISSUE TITLE
[BUG] Saving a widget config does not make it imedialty accessible from the catalog 

### ISSUE THREAD

**Issue by Tomansion** [debiai/debiai#167]
**Describe the bug**
Saving a widget config does not make it imedialty accessible from the catalog 

**To Reproduce**
1. Save new widget conf
2. Open widget catalog
3. Conf ins't available
4. Reload analysis
5. Conf is available

**Expected behavior**
Conf must be available from step 3

**Comment by FadyCoding** [comment]
solved in issue 144, can be closed. thank you

**Comment by Tomansion** [comment]
Fixed in #181
