### ISSUE TITLE
Make the modal close when clicked outside or when escp is pressed

### ISSUE THREAD

**Issue by Tomansion** [debiai/debiai#17]

**Comment by ithiel883** [comment]
Hello, can i work on this issue?

**Comment by Tomansion** [comment]
Thank you for wanting to make a contribution!
We can't take your contribution right now because we're working on our contribution guide.
Sorry for the inconvenience, we didn't anticipate a contribution so early in the project.
I'll let you know as soon as we're ready!

**Comment by ithiel883** [comment]
Thank you @Tomansion, you can assign me this issue so I can get started on it

**Comment by Tomansion** [comment]
Hello @ithiel883, sorry I waited so long to get back to you. I missed your response back then due to a problem with my GitHub notifications.
As I thought you might have forgotten us with the delay, I fixed the problem in PR #82. 

Sorry again about my disorganization, I'm still a newcomer.
