### ISSUE TITLE
Right click override to download image

### ISSUE THREAD

**Issue by FadyCoding** [debiai/debiai#173]
**Is your feature request related to a problem? Please describe.**
When a plot is rendered you are given the possibility in the parameters section to save, load,... and download the plot's image. However usually on a web page you are given the possibility to download it by double clicking on it.

**Describe the solution you'd like**
We'd like to override the current right click logic and be able to download a draw directly after a double click.

**Describe alternatives you've considered**
By testing the problem, you will notice that the right click is done on the html page and not the image.

**Additional context**

**Comment by Tomansion** [comment]
Good idea,thanks for the issue, rewritten in #182
