### ISSUE TITLE
Save interface when starting a new analysis on same Dataframe

### ISSUE THREAD

**Issue by FadyCoding** [debiai/debiai#174]
**Is your feature request related to a problem? Please describe.**
When we start a new analysis with the same data frame slightly modified, for example after deleting biased data, we lose some information from the previous analysis.

**Describe the solution you'd like**

**What could be saved in this case are :** 
- The widgets positions within the window.
- The widgets parameters.
- Launch the drawings, if possible and not too costly.

**Describe alternatives you've considered**

You will notice that this feature works for few widgets like the "**Data distribution**" widget.

**Additional context**

**Comment by Tomansion** [comment]
Saving the widgets parameters and positions within the window already work when exiting an analysis (need to be properly exited)

you can also save a layout : https://debiai.irt-systemx.fr/dashboard/layouts/

Closing because already supported
