### ISSUE TITLE
Dataproviders: Implement (from, to) in get data ID list 

### ISSUE THREAD

**Issue by Tomansion** [debiai/debiai#54]
from and to : provide samples from from to to

Add optional parameters from and to : integer to request, they are send by the front

getDataIdList(),
getDataIdList( from, to )

send parameters to data provider

**Comment by upnico9** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sequençage DP](https://trello.com/c/ZJBQeHei/4-sequen%C3%A7age-dp)
